crud/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name = "herois"

urlpatterns = [
    path('', visaoInicial,name="pagina_inicial"),
    path("classe/<str:filtro_classe>/", visaoPorClasse, name="visao_por_classe"),
    path("heroi/<str:filtro_heroi>/", visaoHeroi, name="visao_por_heroi")
]

overwatch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('crud.urls'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crud/models.py
from django.db import models

# Create your models here.

class Heroi(models.Model):
    imagem = models.ImageField(blank=True, upload_to='heroi')
    apelido = models.CharField(verbose_name="Apelido", max_length=40)
    dificuldade = models.PositiveIntegerField(verbose_name="Dificuldade")
    descricao = models.TextField(verbose_name="Descrição do herói", max_length=800)
    nome_verdadeiro = models.CharField(verbose_name="Nome verdadeiro; idade", max_length=100)
    ocupacao = models.CharField(verbose_name="Ocupação", max_length=100)
    base_operacoes = models.CharField(verbose_name="Base de operações", max_length=100)
    afiliacao = models.CharField(verbose_name="Afiliação", max_length=100)
    historia = models.TextField(verbose_name="História", max_length=10000)
    qtd_habilidades = models.PositiveIntegerField(verbose_name="Quantidade de habilidades")
    fk_funcao = models.ForeignKey('Funcao', on_delete=models.PROTECT, verbose_name="Função")
    habilidade_1 = models.TextField(verbose_name="Habilidade um: ", max_length=500, blank=True)
    habilidade_2 = models.TextField(verbose_name="Habilidade dois ", max_length=500, blank=True)
    habilidade_3 = models.TextField(verbose_name="Habilidade três: ", max_length=500, blank=True)
    habilidade_4 = models.TextField(verbose_name="Habilidade quatro: ", max_length=500, blank=True)
    habilidade_5 = models.TextField(verbose_name="Habilidade cinco : ", max_length=500, blank=True)
    habilidade_6 = models.TextField(verbose_name="Habilidade seis: ", max_length=500, blank=True)
    habilidade_7 = models.TextField(verbose_name="Habilidade sete: ", max_length=500, blank=True)

    def __str__(self):
        return self.apelido


class Funcao(models.Model):
    imagem = models.ImageField()
    nome = models.CharField(verbose_name="Nome da função", max_length=40)
    definiçao = models.TextField(verbose_name="Definição", max_length=300)

    def __str__(self):
        return self.nome

crud/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import *


# Create your views here.

def visaoInicial(request):
    funcoes = Funcao.objects.all()
    herois = Heroi.objects.all()
    contexto = {
        "todas_funcoes": funcoes,
        "herois": herois
    }
    return render(request, 'index.html', contexto)


def visaoPorClasse(request, filtro_classe=None):
    funcoes = Funcao.objects.filter(nome__iexact=filtro_classe)
    herois = Heroi.objects.filter(fk_funcao__nome__iexact=filtro_classe)

    contexto_herois = {
        "todas_funcoes": funcoes,
        "herois": herois
    }
    return render(request, 'visao_por_classe.html', contexto_herois)


def visaoHeroi(request, filtro_heroi=None):
    herois = Heroi.objects.filter(apelido__iexact=filtro_heroi).first()
    contexto = {
        "heroi": herois
    }
    return render(request, 'visao_por_heroi.html', contexto)

crud/templates/heroistanque.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tanque</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
<h1> {% for funcao in todas_funcoes %}
    {{funcao.nome}}

    {% endfor %}</h1>

<table class="table">
  <thead class="thead-dark">
    <tr>
        <th >Nome</th><th>Dificuldade (de 1 à 3)</th><th>Imagem do Heróis ;)</th>

    </tr>
{%for heroi in herois %}

            <td>{{heroi.apelido}}</td>
            <td>{{heroi.dificuldade}}</td>
            <td><img src="{{heroi.imagem.url}}" width="90" height="90" class="img-thumbnail"></td>


    <tr>



    </tr>



   <!--
    -->
              </thead>



{%endfor%}
      </thead>
    </table>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

</body>
</html>

crud/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Overwatch</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <style>

        body{
            background: url('/anexos/heroi/back.jpg');
        }
        .titulo{
            color: #ffffff;
        }
        .grow:hover{
               background-color: #c71585;
               transition: all .2s ease-in-out;
               transform: scale(1.1);
        }
    </style>
</head>
<body>
    <font face="Agency FB" size="5">
        <h1 class="titulo" align="center" >Overwatch</h1>
        <h2 class="titulo"align="center">Exposição de heróis</h2>


      <center>  <div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
          data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
   Modo de exibição
  </button>

  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <a class="dropdown-item" href="#">Dificuldade</a>
    <a class="dropdown-item" href="#">Classes</a>
    <a class="dropdown-item" href="#">Ordem alfabética</a>
  </div>
</div>

      </center>
        <br>


    <table class="table table-striped table-dark">
  <thead class="thead-dark">
  <tr >
        <th>id</th><th>Função</th><th>Imagem representativa ;)</th>
    </tr>
        {% for funcao in todas_funcoes %}
    <tr>
        <td>{{funcao.id}}</td>
        <td>{{funcao.nome}}</td>
        <td><a href="{% url 'herois:visao_por_classe' funcao.nome %}">
            <div class="grow"><img src="{{funcao.imagem.url}}" width="90" height="90" class="img-thumbnail"/></div></a></td>
    </tr>
  </thead>
        {% endfor %}
      </thead>
    </table>



<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

        </font>
</body>
</html>

crud/templates/visao_por_classe.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Classes</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <style>
        body{
            background: url('/anexos/heroi/back.jpg');
        }
        .grow:hover{
               background-color: #c71585;
               transition: all .2s ease-in-out;
               transform: scale(1.1);
        }
    </style>
</head>
<body>

{%for funcao in todas_funcoes%}
<center>
<div class="card" style="width: 18rem;">
 <img class="img-fluid" src="{{funcao.imagem.url}}" alt="{{funcao.nome}}" class="img-thumbnail">
  <div class="card-body">
    <h5 class="card-title">{{funcao.nome}}</h5>
    <p class="card-text">{{funcao.descriçao}}</p>
  </div>
</div>
</center>   <br> <center>
    <font face="Agency FB" size="5">
        <div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
          data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
   Modo de exibição
  </button>


  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <a class="dropdown-item" href="#">Dificuldade</a>
    <a class="dropdown-item" href="#">Classes</a>
    <a class="dropdown-item" href="#">Ordem alfabética</a>
  </div>
</div>
        <a href="http://127.0.0.1:8000/">
            <input type="button" value="Inicio" class="btn btn-secondary" name="fodas a gente nao vai usar"></a>
</center>
<br>
{%endfor%}



<div class="table">
<table class="table table-striped table-dark">
  <thead class="thead-dark">
    <tr>
        <th >Nome</th><th>Dificuldade (de 1 à 3)</th><th>Imagem dos Heróis ;)</th>

    </tr>
{%for heroi in herois %}
 <tr>
            <td>{{heroi.apelido}}</td>
            <td>{{heroi.dificuldade}}</td>
            <td><a href="{% url 'herois:visao_por_heroi' heroi.apelido %}"><div class="grow">
                <img src="{{heroi.imagem.url}}" width="90" height="90" class="img-thumbnail"></div></a></td>


    </tr>

              </thead>

{%endfor%}
      </thead>
    </table>
    </div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

    </font>
</body>
</html>

crud/templates/visao_por_heroi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Herois</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!--<link href="127.0.0.1:8000/anexos/style/style.css" rel="stylesheet" type="text/css">-->
    <style>
        body{
            background-image: url('/anexos/heroi/back.jpg');
        }
        h1{
            color: #ffffff;
        }
    </style>
</head>
<body >

<font face="Agency FB" size="5">
<h1 align="center" >{{heroi.apelido}}</h1>
<center><img class="img-fluid"  src="{{heroi.imagem.url}}" width="65%">

</center>
    <br><center><a href="http://127.0.0.1:8000/">
            <input type="button" value="Inicio" class="btn btn-secondary" name="fodas a gente nao vai usar"></a></center>
<br>

<table class="table table-striped table-dark">
    <thead class="thead-dark">
    <tr>
        <th>
            Descrição do Herói
        </th>
        <th>Dificuldade (de 1 à 3)</th>
    </tr>
    <tr>
        <td>
            {{heroi.descricao}}
        </td>
        <td>{{heroi.dificuldade}}</td>
    </tr>
    </thead>
</table>

<table class="table table-striped table-dark">
    <thead class="thead-dark">

    <tr>
        <th>Ocupação</th>
        <th>Afiliação</th>
        <th>Nome Real, Idade</th>
        <th>Base de Operações</th>
        <th>Função</th>
    </tr>
    <tr>
        <td>{{heroi.ocupacao}}</td>
        <td>{{heroi.afiliacao}}</td>
        <td>{{heroi.nome_verdadeiro}}</td>
        <td>{{heroi.base_operacoes}}</td>
        <td>{{heroi.fk_funcao}}</td>
    </tr>
    </thead>
</table>

<table class="table table-striped table-dark">
    <thead class="thead-dark">
    <tr>
        <th>História</th>
    </tr>
    <tr>
        <td>{{heroi.historia}}</td>
    </tr>
    </thead>
</table>

<div>
<table class="table table-striped table-dark">
    <thead class="thead-dark">
    <tr>
        <th>Habilidades</th>
    </tr>
    <tr>
        <td>{{heroi.habilidade_1}}</td>
        <td>{{heroi.habilidade_2}}</td>
        <td>{{heroi.habilidade_3}}</td>
        <td>{{heroi.habilidade_4}}</td>
        <td>{{heroi.habilidade_5}}</td>
        <td>{{heroi.habilidade_6}}</td>
        <td>{{heroi.habilidade_7}}</td>
    </>
    </thead>
</table>
</div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
    </font>
</body>
</html>